### ISSUE TITLE
Backport changes from Kalablog8

### ISSUE THREAD

**Issue by hawkeyetwolf** [kalamuna/drupal-project#14]
In the future, we should make changes here and then just pull them into the other projects that fork off this one. cc @RobLoach

**Comment by RobLoach** [comment]
YESYSYEYSYYEYSEYSYEYESYEYESYEYSEYYEES

Just needed to get it working to make sprint.

**Comment by derekderaps** [comment]
Totes! And I think you already did the backport in #10, so closing this one out. Thanks @RobLoach!

**Comment by RobLoach** [comment]
Reopening this bring the changes upstream.

**Comment by mikemccaffrey** [comment]
Don't think this is needed anymore with the new branch.
