### ISSUE TITLE
Add Pantheon Settings

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/drupal-project#29]
https://github.com/pantheon-systems/drops-8/blob/master/sites/default/settings.pantheon.php

JohnO did it on k3n:
https://github.com/kalamuna/k3n/blob/master/web/sites/default/settings.php

**Comment by labboy0276** [comment]
also add this into settings.php

// Pantheon Settings
if (isset($_ENV['PANTHEON_ENVIRONMENT'])) {
  /**
   * Include the Pantheon-specific settings file.
   *
   * n.b. The settings.pantheon.php file makes some changes
   *      that affect all envrionments that this site
   *      exists in.  Always include this file, even in
   *      a local development environment, to insure that
   *      the site settings remain consistent.
   */
  include __DIR__ . "/settings.pantheon.php";
}

**Comment by mikemccaffrey** [comment]
Fixed in new version. It pulls the pantheon settings from the drops repo.
