### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by hawkeyetwolf** [kalamuna/drupal-project#55]
Consider using [this](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2) as a template. But that means we'd be divorcing our README from the upstream. Hmmm.... Worth it?

**Comment by RobLoach** [comment]
Agreed... The template is something we could even push upstream.

As for the kalamuna/drupal-project one, does seem to need some good docs. More around doing a checkout with git rather than composer create-project too.

**Comment by mikemccaffrey** [comment]
@RobLoach I rewrote the README with the new version. Is there anything sections from the template above that you think are important to add as well?

**Comment by RobLoach** [comment]
It's mucho improved! There are always more sections we could improve on, but I think this is a great starting point... Nice work :+1:
