### ISSUE TITLE
Base Styleguide

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/drupal-project#67]
Bring over Base Styleguide (lots of example components) from NB.

https://github.com/kalamuna/naturebridge/tree/master/web/themes/custom/naturebridge/kalastatic

And the General Setup.

- Sample Components!

**Comment by mikemccaffrey** [comment]
@RobLoach Any ideas how we want to have a kalastatic version of drupal-project without needing it installed on all sites? I'd suggest adding them to the package.json file and commenting them out by default, but json doesn't support comments.
